name: Test Coverage

on:
  push:
    branches:
      - main
      - develop
      - feat/**
  pull_request:
    branches:
      - main
      - develop
      - feat/**

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./WebAPI.Tests/WebAPI.Tests.csproj

      - name: Run tests with coverage
        run: |
          dotnet test ./WebAPI.Tests/WebAPI.Tests.csproj \
            --logger "trx;LogFileName=test-results.trx" \
            --collect:"XPlat Code Coverage" \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=./TestResults/
        continue-on-error: true # Fortsæt selv ved fejl for debugging

      - name: Debug generated files
        run: |
          ls -la ./WebAPI.Tests/TestResults
          find . -name "*.trx"
          find . -name "*.xml"
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./WebAPI.Tests/TestResults/test-results.trx
        if: always()

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./WebAPI.Tests/TestResults/coverage.cobertura.xml
        if: always()