name: Test Coverage

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./WebAPI.Tests/WebAPI.Tests.csproj

      - name: Run tests with coverage
        run: |
          dotnet test ./WebAPI.Tests/WebAPI.Tests.csproj \
            --logger "trx;LogFileName=test-results.trx" \
            --collect:"XPlat Code Coverage" \
            /p:CoverletOutputFormat=cobertura

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "**/test-results.trx"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: "**/coverage.cobertura.xml"
