name: Testing and Coverage Report

on:
  push:
  pull_request:

jobs:
  build-and-unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore

      - name: Test Reports
        uses: xportation/junit-coverage-report@main
        with:
          junit-path: ./reports/unit/unit.xml  
          coverage-path: ./reports/coverage/coverage.xml