name: Test Coverage

on:
  push:
    branches:
      - main
      - develop
      - feat/**
  pull_request:
    branches:
      - main
      - develop
      - feat/**

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Debug .NET environment
        run: |
          dotnet --version
          dotnet --info
        if: always()

      - name: Debug project structure
        run: |
          pwd
          ls -la
          ls -la ./WebAPI.Tests || echo "WebAPI.Tests directory not found"
          find . -name "*.csproj"
        if: always()

      - name: Restore dependencies
        run: dotnet restore ./WebAPI.Tests/WebAPI.Tests.csproj
        continue-on-error: true

      - name: Debug after restore
        run: ls -la ./WebAPI.Tests
        if: always()

      - name: Debug test project contents
        run: |
          find ./WebAPI.Tests -name "*.cs" -exec grep -H "Test" {} \;
        if: always()

      - name: Run tests with coverage
        run: |
          dotnet test ./WebAPI.Tests/WebAPI.Tests.csproj \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=./WebAPI.Tests/TestResults/coverage.opencover.xml \
            --collect:"XPlat Code Coverage" \
            --logger "trx;LogFileName=./WebAPI.Tests/TestResults/test-results.trx" \
            --verbosity detailed
        continue-on-error: true

      - name: Debug test output
        run: cat ./WebAPI.Tests/TestResults/WebAPI.Tests/TestResults/*/test-results.trx || echo "No TRX file found"
        if: always()

      - name: Debug generated files
        run: |
          ls -la ./WebAPI.Tests/TestResults || echo "TestResults directory not found"
          ls -la ./WebAPI.Tests/TestResults/WebAPI.Tests/TestResults || echo "Nested TestResults directory not found"
          find . -name "*.trx"
          find . -name "*.xml"
          find . -name "coverage.*"
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./WebAPI.Tests/TestResults/WebAPI.Tests/TestResults/*/test-results.trx
        if: always()

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./WebAPI.Tests/TestResults/WebAPI.Tests/TestResults/*/coverage.opencover.xml
        if: always()